language: java
jdk: openjdk8
dist: trusty
before_install:
  - if [ -n "$encrypted_49258d069291_key" ]; then openssl aes-256-cbc -K $encrypted_49258d069291_key -iv $encrypted_49258d069291_iv -in .travis/settings_codesigning.tar.enc -out .travis/settings_codesigning.tar -d; tar xf .travis/settings_codesigning.tar -C .travis; fi
  - if [ -f .travis/codesigning.asc ]; then gpg --fast-import .travis/codesigning.asc; fi
install: true
addons:
  sonarcloud:
    organization: "worksapplications"
    token:
      secure: "JQ6x+3Wd9hqUxaYVCjBwLwxbvkGcCQyOwLEVL2JtMi+rzuWJjpLzmxU8s8R4Uqym8sSG5eFw+gk2909vg6ItghynTionnDgF83K/ALeaIg1tUjEjv+cNYC4v724fAFjItYQmZHiZRyV4OKESR2JpRanYR21MQrEOwwsIlYORntvEoSnx+qUg6NgB/VgTcWbC9fCS2kbR5B8xh+IHczlphhZCGgMP+Bvv2NxzB/7UhKNdWDRAuGzvcHD9MgTzdPH6YcsP47506BnkZ0b7k9V5U1ZngHZwo+3fy9ZuTEM/rozxadf13wx95rzcT0imFF5ex5JIgLTmctWfLXN6uS7YvgP9krdRyqI2V+bJgvOlPnKwlPGqf+IuVY20Eq4Z2GKWjTV6xwzZL53slWNW3ECz14GDpSfQYHXwo8lH/s4jLe7pYESX8VruONz2e9OqNF8NR+kBNTEmOBDCI6sJtLqgHae9ZpUMl5yuNARwJKFvkOO4TEYO3lnHhMZ61sM4T7rHf3HewqYvK46eY1y7jG5IPXBgA3khbD/RZz2TsN93I7zfY+lpShC5EYMbt+v2+H7q9ULB/UYffVpLUB4L6NStGoRAvyZHmen8bf5PzsQO/OremmfPkJ/D/WXI6gYQ2QcPzhXx74r3Pl7zxC7mQ4xGjUXRkv9WsOL//T3K+xoXdwI="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test -B
after_success:
  - mvn sonar:sonar -B
deploy:
  - provider: script
    script: mvn clean deploy -P release -B --settings .travis/settings.xml
    skip_cleanup: true
    on:
      branch: develop
cache:
  directories:
    - $HOME/.m2/repository/
