language: java
jdk: openjdk8
dist: trusty
before_install:
  - if [ -n "$encrypted_49258d069291_key" ]; then openssl aes-256-cbc -K $encrypted_49258d069291_key -iv $encrypted_49258d069291_iv -in .travis/settings_codesigning.tar.enc -out .travis/settings_codesigning.tar -d; tar xf .travis/settings_codesigning.tar -C .travis; fi
  - if [ -f .travis/codesigning.asc ]; then gpg --fast-import .travis/codesigning.asc; fi
install: true
addons:
  sonarcloud:
    organization: "worksapplications"
    token:
      secure: "gQs2Bzdg5RxU0StNOC8+v3ZrIEjySprl3d7Wh1uSddJzU78JN2PSOgo1eWs8RSscxhVOLc7gmvgGrFO9jaOwDE/JM2SHK9ZbTHg1aCls+n0/JB5aV1AQ8dMDHjUMCC8lvT5l+EU2N0kHDgBhpyCTUGdaQmSOj9Z4tVqFmCIZkUWre4JNX9v2MZJNbqmd4y43+GHTrdQJbbqyrbzO2ihtYdXnvcX+EIBs4Fq8u38/6KvWXlP6Sn+sinlKzvQbnQQxNP58PsvPm49OWDEMmTpTJZTi8W5qf97PeIK56hubmzxAhb7oVcgZFvBTosiECplLuTgaB4p6Fj/ZXhHWWx69350L39RqA+H4w6cpbnTmiDhTl6DfJYB9k9dnkSUSpwL+7afH6cSzj+iZko8Hu0vnzqgIXzOXzH8jOgtZMDMBWdvXM7CdPmbobTJZRo2tRoQKJQoVns8rLDRm5cC7Reon17nlun9rHC5ZkafKWe2/j5Ic/5C5N62vzY7Cz77ljV1GIrro+YAkE/f7JViOvxWG1u39+AyoCdWWF8xdMbzbdfUdmGCbcPYOjgDnjAqhAk0HutIkLsqRffHDhyi2kvld+Rli3w12jo05tvTDGIj5vjJnkWC5d4ZFn2/RpsYk5Hzt9CAMkxN6DUNfl5MLf8WQGpSBI29GwW8iPo6xpyB6dlk="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test -B
after_success:
  - mvn sonar:sonar -B
deploy:
  - provider: script
    script: mvn clean deploy -P release -B --settings .travis/settings.xml
    skip_cleanup: true
    on:
      branch: develop
cache:
  directories:
    - $HOME/.m2/repository/
